### ISSUE TITLE
username is not defined when used multiTemplate

### ISSUE THREAD

**Issue by szguomy** [macarthuror/parse-smtp-template#16]
hello,  I used "parse-smtp-template": "^2.2.0", it works well on "template: true",but failed on "multiTemplate: true"

here is my configure:
    emailAdapter: {
        module: 'parse-smtp-template',
        options: {
            secure: true,
            port: 465,
            host: "xxxxxx",
            user: "xxxxxx",
            password: "xxxxxx",
            fromAddress: 'xxxxxxx',

            //template: true,
            //templatePath: "templates/main.html",
            multiTemplate: true,
            confirmTemplatePath: "templates/confirmTemplate.html",
            //passwordTemplatePath: "templates/passwordTemplate.html",
            passwordTemplatePath: "templates/main.html",

            passwordOptions: {
                subject: "Password reset",
                body: "password recovery email",
                btn: "Reset Password",
                others: {
                  test:"test"
                }
            },
            confirmOptions: {
                subject: "verify email",
                body: "email confirmation",
                btn: "Confirm Email"
            },
        }
    },

it report errors after request email:

{"level":"error","message":"Uncaught internal server error. username is not defined","stack":"ReferenceError: username is not defined\n    at eval (eval at sendPasswordResetEmail (/root/www/node_modules/parse-smtp-template/index.js:292:24), <anonymous>:264:60)\n    at Object.sendPasswordResetEmail (/root/www/node_modules/parse-smtp-template/index.js:292:24)\n    at UserController.sendPasswordResetEmail (/root/www/node_modules/parse-server/lib/Controllers/UserController.js:295:20)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-09-02T04:52:21.810Z"}

**Comment by szguomy** [comment]
resolved.  in multiTemplate, need use  user.username
