### ISSUE TITLE
Parse server crashes if mail doesn't exist

### ISSUE THREAD

**Issue by R3D347HR4Y** [macarthuror/parse-smtp-template#23]
I'm encountering a problem with this lib, whenever a user signs up with an email /domain that does not exist, the entire parse server just crashes, I'm guessing it's because it's trying to send to an unknown or invalid domain
Maybe a try catch would fix that, or maybe an exception needs to be made for OVH idk

Here is the error I get:
```
Error: queryA ETIMEOUT ssl0.ovh.net
     at QueryReqWrap.onresolve [as oncomplete] (node:dns:213:19) {
   errno: undefined,
   code: 'EDNS',
   syscall: 'queryA',
   hostname: 'ssl0.ovh.net',
   command: 'CONN'
 }
```

**Comment by macarthuror** [comment]
Please share the version of Parse and the configuration are using.

**Comment by chlangbein** [comment]
As I have the same problem:
Parse server version is 6.2.0, if I try to send to not existing mail account parse crashes. I think the creation of user should be stopped here ...

> 
[155157] parse-server running on http://localhost:1337/parse
/usr/local/share/.config/yarn/global/node_modules/parse-server/lib/ParseServer.js:251
          throw err;
          ^

Error: Can't send mail - all recipients were rejected: 550 5.1.1 <mail@example.com>: Recipient address rejected: User unknown in virtual mailbox table
    at SMTPConnection._formatError (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionRCPT (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:1626:28)
    at SMTPConnection.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:1579:30)
    at SMTPConnection._processResponse (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at SMTPConnection._onSocketData (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'EENVELOPE',
  response: '550 5.1.1 <mail@example.com>: Recipient address rejected: User unknown in virtual mailbox table',
  responseCode: 550,
  command: 'RCPT TO',
  rejected: [ 'mail@example.com' ],
  rejectedErrors: [
    Error: Recipient command failed: 550 5.1.1 <mail@example.com>: Recipient address rejected: User unknown in virtual mailbox table
        at SMTPConnection._formatError (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
        at SMTPConnection._actionRCPT (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:1612:24)
        at SMTPConnection.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:1579:30)
        at SMTPConnection._processResponse (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
        at SMTPConnection._onData (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
        at SMTPConnection._onSocketData (/usr/local/share/.config/yarn/global/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
        at TLSSocket.emit (node:events:513:28)
        at addChunk (node:internal/streams/readable:324:12)
        at readableAddChunk (node:internal/streams/readable:297:9)
        at Readable.push (node:internal/streams/readable:234:10) {
      code: 'EENVELOPE',
      response: '550 5.1.1 <mail@example.com>: Recipient address rejected: User unknown in virtual mailbox table',
      responseCode: 550,
      command: 'RCPT TO',
      recipient: 'mail@example.com'
    }
  ]
}

Node.js v18.16.0>

**Comment by macarthuror** [comment]
It's not a problem with the package.

**Comment by macarthuror** [comment]
It's not a problem with the package.
